import random

# Data Preparation
test_questions = [
    {"question": "What is the capital of India?", "answer": "New Delhi"},
    {"question": "Who is known as the Father of the Nation in India?", "answer": "Mahatma Gandhi"},
    {"question": "What is the national animal of India?", "answer": "Tiger"},
    {"question": "In which year did India gain independence from British rule?", "answer": "1947"},
    {"question": "What is the national sport of India?", "answer": "Hockey"},
    {"question": "Who was the first Prime Minister of India?", "answer": "Jawaharlal Nehru"},
    {"question": "Which Indian city is known as the Silicon Valley of India?", "answer": "Bangalore"},
    {"question": "What is the official language of India?", "answer": "Hindi"},
    {"question": "Which river is considered the holiest in India?", "answer": "Ganges"},
    {"question": "What is the currency of India?", "answer": "Indian Rupee"},
    {"question": "Which festival is celebrated as the festival of lights in India?", "answer": "Diwali"},
    {"question": "What is the national flower of India?", "answer": "Lotus"},
    {"question": "Who is the current Prime Minister of India?", "answer": "Narendra Modi"},
    {"question": "What is the highest mountain peak in the world?", "answer": "Mount Everest"},
    {"question": "Who wrote 'To Kill a Mockingbird'?", "answer": "Harper Lee"},
    {"question": "What is the largest planet in our solar system?", "answer": "Jupiter"},
    {"question": "What is the capital of Japan?", "answer": "Tokyo"},
    {"question": "Who painted the Mona Lisa?", "answer": "Leonardo da Vinci"},
    {"question": "What is the smallest prime number?", "answer": "2"},
    {"question": "What year did the Titanic sink?", "answer": "1912"},
    {"question": "What is the chemical symbol for gold?", "answer": "Au"},
    {"question": "Who is known as the father of modern physics?", "answer": "Albert Einstein"},
    {"question": "What is the tallest mountain in the world?", "answer": "Mount Everest"},
    {"question": "What is the largest ocean on Earth?", "answer": "Pacific Ocean"},
    {"question": "What is the main ingredient in guacamole?", "answer": "Avocado"},
    {"question": "Who wrote '1984'?", "answer": "George Orwell"},
    {"question": "What is the capital of Canada?", "answer": "Ottawa"},
    {"question": "Who was the first person to walk on the moon?", "answer": "Neil Armstrong"},
    {"question": "What is the hardest natural substance on Earth?", "answer": "Diamond"},
    {"question": "Who discovered penicillin?", "answer": "Alexander Fleming"},
    {"question": "What is the currency of Japan?", "answer": "Yen"},
    {"question": "What is the capital of Australia?", "answer": "Canberra"},
    {"question": "Who wrote 'Pride and Prejudice'?", "answer": "Jane Austen"},
    {"question": "What is the square root of 144?", "answer": "12"},
    {"question": "What is the longest river in the world?", "answer": "Nile"},
    {"question": "Who was the first president of the United States?", "answer": "George Washington"},
    {"question": "What is the chemical symbol for water?", "answer": "H2O"},
    {"question": "What is the capital of Germany?", "answer": "Berlin"},
    {"question": "Who discovered electricity?", "answer": "Benjamin Franklin"},
    {"question": "What is the smallest country in the world?", "answer": "Vatican City"},
    {"question": "What is the tallest building in the world?", "answer": "Burj Khalifa"},
    {"question": "What is the national flower of Japan?", "answer": "Cherry Blossom"},
    {"question": "What is the primary language spoken in Brazil?", "answer": "Portuguese"},
    {"question": "What year did World War I begin?", "answer": "1914"},
    {"question": "Who invented the telephone?", "answer": "Alexander Graham Bell"},
    {"question": "Who wrote 'The Great Gatsby'?", "answer": "F. Scott Fitzgerald"},
    {"question": "What is the largest desert in the world?", "answer": "Sahara"},
    {"question": "What is the capital of Spain?", "answer": "Madrid"},
    {"question": "What is the longest-running TV show?", "answer": "The Simpsons"},
    {"question": "Who invented the light bulb?", "answer": "Thomas Edison"},
    {"question": "What is the capital of Italy?", "answer": "Rome"},
    {"question": "What is the most spoken language in the world?", "answer": "Mandarin"},
    {"question": "What year did World War II end?", "answer": "1945"},
    {"question": "Who painted the Sistine Chapel?", "answer": "Michelangelo"},
    {"question": "What is the largest island in the world?", "answer": "Greenland"},
    {"question": "What is the name of the longest mountain range in the world?", "answer": "Andes"},
    {"question": "What is the boiling point of water?", "answer": "100°C"},
    {"question": "Who invented the airplane?", "answer": "Wright Brothers"},
    {"question": "What is the official language of Egypt?", "answer": "Arabic"},
    {"question": "What is the chemical symbol for oxygen?", "answer": "O"},
    {"question": "Who wrote 'Moby Dick'?", "answer": "Herman Melville"},
    {"question": "Who is known as the 'father of modern chemistry'?", "answer": "Antoine Lavoisier"},
    {"question": "What is the capital of India?", "answer": "New Delhi"},
    {"question": "Who discovered the theory of relativity?", "answer": "Albert Einstein"},
    {"question": "What is the largest city in the United States by population?", "answer": "New York City"},
    {"question": "What is the currency of the United Kingdom?", "answer": "Pound Sterling"},
    {"question": "What is the hardest rock?", "answer": "Diamond"},
    {"question": "Who was the first woman to win a Nobel Prize?", "answer": "Marie Curie"},
    {"question": "What is the most populous country in the world?", "answer": "China"},
    {"question": "Who wrote 'The Catcher in the Rye'?", "answer": "J.D. Salinger"},
    {"question": "What is the capital of Russia?", "answer": "Moscow"},
    {"question": "Who invented the printing press?", "answer": "Johannes Gutenberg"},
    {"question": "What is the national animal of Australia?", "answer": "Kangaroo"},
    {"question": "What is the currency of the United States?", "answer": "Dollar"},
    {"question": "What is the square root of 81?", "answer": "9"},
    {"question": "Who is known as the 'father of modern economics'?", "answer": "Adam Smith"},
    {"question": "What is the capital of South Korea?", "answer": "Seoul"},
    {"question": "What is the name of the longest river in South America?", "answer": "Amazon River"},
    {"question": "What is the tallest waterfall in the world?", "answer": "Angel Falls"},
    {"question": "Who discovered the law of gravity?", "answer": "Isaac Newton"},
    {"question": "What is the largest country by area?", "answer": "Russia"},
    {"question": "Who invented the steam engine?", "answer": "James Watt"},
    {"question": "What is the largest land animal?", "answer": "African Elephant"},
    {"question": "What is the national sport of Japan?", "answer": "Sumo Wrestling"},
    {"question": "What is the largest continent?", "answer": "Asia"},
    {"question": "What is the capital of Egypt?", "answer": "Cairo"},
    {"question": "Who wrote 'Frankenstein'?", "answer": "Mary Shelley"},
    {"question": "What is the deepest ocean in the world?", "answer": "Pacific Ocean"},
    {"question": "What is the chemical symbol for carbon?", "answer": "C"},
    {"question": "Who is known as the 'father of modern chemistry'?", "answer": "Antoine Lavoisier"},
    {"question": "What is the capital of Brazil?", "answer": "Brasília"},
    {"question": "Who invented the computer?", "answer": "Charles Babbage"},
    {"question": "What is the longest mountain range in North America?", "answer": "Rocky Mountains"},
    {"question": "What is the square root of 169?", "answer": "13"},
    {"question": "What is the capital of Turkey?", "answer": "Ankara"},
    {"question": "Who was the first female prime minister of the United Kingdom?", "answer": "Margaret Thatcher"},
    {"question": "What is the largest country in Africa?", "answer": "Algeria"},
    {"question": "What is the main ingredient in sushi?", "answer": "Rice"},
    {"question": "Who wrote 'Crime and Punishment'?", "answer": "Fyodor Dostoevsky"},
    {"question": "What is the capital of China?", "answer": "Beijing"},
    {"question": "Who developed the theory of evolution?", "answer": "Charles Darwin"},
    {"question": "What is the largest lake in Africa?", "answer": "Lake Victoria"},
    {"question": "Who wrote 'War and Peace'?", "answer": "Leo Tolstoy"},
    {"question": "What is the tallest building in the United States?", "answer": "One World Trade Center"},
    {"question": "What is the currency of France?", "answer": "Euro"},
    {"question": "What is the national flower of the United States?", "answer": "Rose"},
    {"question": "Who invented the polio vaccine?", "answer": "Jonas Salk"},
    {"question": "What is the longest river in Europe?", "answer": "Volga River"},
    {"question": "What is the national animal of India?", "answer": "Tiger"},
    {"question": "What is the square root of 225?", "answer": "15"},
    {"question": "Who wrote 'Jane Eyre'?", "answer": "Charlotte Bronte"},
    {"question": "What is the capital of Mexico?", "answer": "Mexico City"},
    {"question": "What is the name of the largest volcano in the world?", "answer": "Mauna Loa"},
    {"question": "Who invented the refrigerator?", "answer": "Jacob Perkins"},
    {"question": "What is the name of the largest island in the Mediterranean Sea?", "answer": "Sicily"},
    {"question": "What is the boiling point of water in Fahrenheit?", "answer": "212°F"},
    {"question": "Who invented the radio?", "answer": "Guglielmo Marconi"},
    {"question": "What is the national dish of Spain?", "answer": "Paella"},
    {"question": "Who wrote 'The Odyssey'?", "answer": "Homer"},
    {"question": "What is the capital of Thailand?", "answer": "Bangkok"},
    {"question": "Who invented the washing machine?", "answer": "Jacob Christian Schäffer"},
    {"question": "What is the name of the highest peak in Africa?", "answer": "Mount Kilimanjaro"},
    {"question": "What is the national animal of Russia?", "answer": "Brown Bear"},
    {"question": "What is the square root of 196?", "answer": "14"},
    {"question": "Who wrote 'Les Misérables'?", "answer": "Victor Hugo"},
    {"question": "What is the capital of Argentina?", "answer": "Buenos Aires"},
    {"question": "What is the national sport of Canada?", "answer": "Ice Hockey"},
    {"question": "Who invented the safety pin?", "answer": "Walter Hunt"},
    {"question": "What is the currency of Italy?", "answer": "Euro"},
    {"question": "What is the national flower of Australia?", "answer": "Golden Wattle"},
    {"question": "Who wrote 'Wuthering Heights'?", "answer": "Emily Bronte"},
    {"question": "What is the name of the largest desert in Asia?", "answer": "Gobi Desert"},
    {"question": "What is the boiling point of water in Celsius?", "answer": "100°C"},
    {"question": "Who invented the microphone?", "answer": "Emile Berliner"},
    {"question": "What is the capital of Saudi Arabia?", "answer": "Riyadh"},
    {"question": "Who invented the telegraph?", "answer": "Samuel Morse"},
    {"question": "What is the national animal of Germany?", "answer": "Eagle"},
    {"question": "What is the square root of 256?", "answer": "16"},
    {"question": "Who wrote 'The Count of Monte Cristo'?", "answer": "Alexandre Dumas"},
    {"question": "What is the capital of Colombia?", "answer": "Bogotá"},
    {"question": "What is the national sport of Brazil?", "answer": "Football"},
    {"question": "Who invented the sewing machine?", "answer": "Elias Howe"},
    {"question": "What is the currency of Spain?", "answer": "Euro"},
    {"question": "What is the national flower of Canada?", "answer": "Maple Leaf"},
    {"question": "Who wrote 'Dracula'?", "answer": "Bram Stoker"},
    {"question": "What is the name of the largest glacier in the world?", "answer": "Lambert Glacier"},
    {"question": "What is the boiling point of water in Kelvin?", "answer": "373.15K"},
    {"question": "Who invented the typewriter?", "answer": "Christopher Sholes"},
    {"question": "What is the national dish of Italy?", "answer": "Pasta"},
    {"question": "Who wrote 'The Hobbit'?", "answer": "J.R.R. Tolkien"},
    {"question": "What is the capital of South Africa?", "answer": "Pretoria"},
    {"question": "Who invented the fax machine?", "answer": "Alexander Bain"},
    {"question": "What is the name of the largest cave in the world?", "answer": "Son Doong Cave"},
    {"question": "What is the national animal of China?", "answer": "Giant Panda"},
    {"question": "What is the square root of 324?", "answer": "18"},
    {"question": "Who wrote 'The Divine Comedy'?", "answer": "Dante Alighieri"},
    {"question": "What is the capital of Chile?", "answer": "Santiago"},
    {"question": "What is the national sport of India?", "answer": "Field Hockey"},
    {"question": "Who invented the bicycle?", "answer": "Karl von Drais"},
    {"question": "What is the currency of Australia?", "answer": "Australian Dollar"},
    {"question": "What is the national flower of Japan?", "answer": "Cherry Blossom"},
    {"question": "Who wrote 'The Picture of Dorian Gray'?", "answer": "Oscar Wilde"},
    {"question": "What is the name of the largest waterfall in the world?", "answer": "Victoria Falls"},
    {"question": "What is the boiling point of water in Fahrenheit?", "answer": "212°F"},
    {"question": "Who invented the internet?", "answer": "Tim Berners-Lee"},
    {"question": "What is the national dish of Japan?", "answer": "Sushi"},
    {"question": "Who wrote 'The Canterbury Tales'?", "answer": "Geoffrey Chaucer"},
    {"question": "What is the capital of Greece?", "answer": "Athens"},
    {"question": "Who invented the computer mouse?", "answer": "Douglas Engelbart"},
    {"question": "What is the name of the largest reef in the world?", "answer": "Great Barrier Reef"},
    {"question": "What is the national animal of the United States?", "answer": "Bald Eagle"},
    {"question": "What is the square root of 441?", "answer": "21"},
    {"question": "Who wrote 'Don Quixote'?", "answer": "Miguel de Cervantes"},
    {"question": "What is the capital of Peru?", "answer": "Lima"},
    {"question": "What is the national sport of New Zealand?", "answer": "Rugby"},
    {"question": "Who invented the electric motor?", "answer": "Michael Faraday"},
    {"question": "What is the currency of Switzerland?", "answer": "Swiss Franc"},
    {"question": "What is the national flower of the United Kingdom?", "answer": "Rose"},
    {"question": "Who wrote 'The Iliad'?", "answer": "Homer"},
    {"question": "What is the name of the largest island in the Caribbean?", "answer": "Cuba"},
    {"question": "What is the boiling point of water in Kelvin?", "answer": "373.15K"},
    {"question": "Who invented the printing press?", "answer": "Johannes Gutenberg"},
    {"question": "What is the national dish of Mexico?", "answer": "Tacos"},
    {"question": "Who wrote 'The Aeneid'?", "answer": "Virgil"},
    {"question": "What is the capital of Sweden?", "answer": "Stockholm"},
    {"question": "Who invented the digital camera?", "answer": "Steven Sasson"},
    {"question": "What is the name of the largest island in the Mediterranean?", "answer": "Sicily"},
    {"question": "What is the national animal of France?", "answer": "Rooster"},
    {"question": "What is the square root of 484?", "answer": "22"},
    {"question": "Who wrote 'The Brothers Karamazov'?", "answer": "Fyodor Dostoevsky"},
    {"question": "What is the capital of Norway?", "answer": "Oslo"},
    {"question": "What is the national sport of Pakistan?", "answer": "Field Hockey"},
    {"question": "Who invented the first airplane?", "answer": "Wright Brothers"},
    {"question": "What is the currency of Germany?", "answer": "Euro"},
    {"question": "What is the national flower of India?", "answer": "Lotus"},
    {"question": "Who wrote 'The Adventures of Huckleberry Finn'?", "answer": "Mark Twain"},
    {"question": "What is the name of the largest lake in the world?", "answer": "Caspian Sea"},
    {"question": "What is the boiling point of water in Celsius?", "answer": "100°C"},
    {"question": "Who invented the telephone?", "answer": "Alexander Graham Bell"},
    {"question": "What is the national dish of China?", "answer": "Peking Duck"},
    {"question": "Who wrote 'The Metamorphosis'?", "answer": "Franz Kafka"},
    {"question": "What is the capital of Finland?", "answer": "Helsinki"},
    {"question": "Who invented the light bulb?", "answer": "Thomas Edison"},
    {"question": "What is the national animal of Italy?", "answer": "Wolf"},
    {"question": "What is the square root of 529?", "answer": "23"},
    {"question": "Who wrote 'The Old Man and the Sea'?", "answer": "Ernest Hemingway"},
    {"question": "What is the capital of Denmark?", "answer": "Copenhagen"},
    {"question": "What is the national sport of Russia?", "answer": "Bandy"},
    {"question": "Who invented the first computer?", "answer": "Charles Babbage"},
    {"question": "What is the currency of Russia?", "answer": "Ruble"},
    {"question": "What is the national flower of Canada?", "answer": "Maple Leaf"},
    {"question": "Who wrote 'The Great Gatsby'?", "answer": "F. Scott Fitzgerald"},
    {"question": "What is the name of the largest desert in the world?", "answer": "Sahara Desert"},
    {"question": "What is the boiling point of water in Fahrenheit?", "answer": "212°F"},
    {"question": "Who invented the steam engine?", "answer": "James Watt"},
    {"question": "What is the national dish of Thailand?", "answer": "Pad Thai"},
    {"question": "Who wrote 'The Odyssey'?", "answer": "Homer"},
    {"question": "What is the capital of Ireland?", "answer": "Dublin"},
    {"question": "Who invented the first automobile?", "answer": "Karl Benz"},
    {"question": "What is the national animal of Australia?", "answer": "Kangaroo"},
    {"question": "What is the square root of 576?", "answer": "24"},
    {"question": "Who wrote 'The Sound and the Fury'?", "answer": "William Faulkner"},
    {"question": "What is the capital of the Netherlands?", "answer": "Amsterdam"},
    {"question": "What is the national sport of Canada?", "answer": "Ice Hockey"},
    {"question": "Who invented the first electric battery?", "answer": "Alessandro Volta"},
    {"question": "What is the currency of Japan?", "answer": "Yen"},
    {"question": "What is the national flower of Japan?", "answer": "Cherry Blossom"},
    {"question": "Who wrote 'Moby-Dick'?", "answer": "Herman Melville"},
    {"question": "What is the name of the largest island in the world?", "answer": "Greenland"},
    {"question": "What is the boiling point of water in Kelvin?", "answer": "373.15K"},
    {"question": "Who invented the internet?", "answer": "Tim Berners-Lee"},
    {"question": "What is the national dish of Japan?", "answer": "Sushi"},
    {"question": "Who wrote 'The Canterbury Tales'?", "answer": "Geoffrey Chaucer"},
    {"question": "What is the capital of Greece?", "answer": "Athens"},
    {"question": "Who invented the first electronic computer?", "answer": "John Atanasoff"},
    {"question": "What is the name of the largest coral reef system in the world?", "answer": "Great Barrier Reef"},
    {"question": "What is the national animal of India?", "answer": "Bengal Tiger"},
    {"question": "What is the square root of 625?", "answer": "25"},
    {"question": "Who wrote 'War and Peace'?", "answer": "Leo Tolstoy"},
    {"question": "What is the capital of Argentina?", "answer": "Buenos Aires"},
    {"question": "What is the national sport of New Zealand?", "answer": "Rugby"},
    {"question": "Who invented the electric motor?", "answer": "Michael Faraday"},
    {"question": "What is the currency of Switzerland?", "answer": "Swiss Franc"},
    {"question": "What is the national flower of France?", "answer": "Lily"},
    {"question": "Who wrote 'Les Misérables'?", "answer": "Victor Hugo"},
    {"question": "What is the capital of Colombia?", "answer": "Bogotá"},
    {"question": "What is the national sport of Brazil?", "answer": "Football"},
    {"question": "Who invented the sewing machine?", "answer": "Elias Howe"},
    {"question": "What is the currency of Italy?", "answer": "Euro"},
    {"question": "What is the national flower of the United Kingdom?", "answer": "Rose"},
    {"question": "Who wrote 'The Brothers Karamazov'?", "answer": "Fyodor Dostoevsky"},
    {"question": "What is the capital of Turkey?", "answer": "Ankara"},
    {"question": "Who wrote '1984'?", "answer": "George Orwell"},
    {"question": "What is the currency of Spain?", "answer": "Euro"},
    {"question": "Who wrote 'Pride and Prejudice'?", "answer": "Jane Austen"},
    {"question": "What is the capital of Brazil?", "answer": "Brasília"},
    {"question": "What is the largest continent?", "answer": "Asia"},
    {"question": "Who wrote 'The Hobbit'?", "answer": "J.R.R. Tolkien"},
    {"question": "What is the capital of South Africa?", "answer": "Pretoria"},
    {"question": "Who wrote 'The Sound and the Fury'?", "answer": "William Faulkner"},
    {"question": "What is the capital of the Netherlands?", "answer": "Amsterdam"},
    {"question": "What is the national flower of Canada?", "answer": "Maple Leaf"},
    {"question": "Who wrote 'The Divine Comedy'?", "answer": "Dante Alighieri"},
    {"question": "What is the capital of Sweden?", "answer": "Stockholm"},
    {"question": "What is the national flower of the United States?", "answer": "Rose"},
    {"question": "Who wrote 'The Iliad'?", "answer": "Homer"},
    {"question": "What is the capital of Norway?", "answer": "Oslo"},
    {"question": "Who wrote 'Don Quixote'?", "answer": "Miguel de Cervantes"},
    {"question": "What is the national flower of India?", "answer": "Lotus"},
    {"question": "Who wrote 'The Old Man and the Sea'?", "answer": "Ernest Hemingway"},
    {"question": "What is the capital of Denmark?", "answer": "Copenhagen"},
    {"question": "Who wrote 'The Picture of Dorian Gray'?", "answer": "Oscar Wilde"},
    {"question": "What is the national flower of Japan?", "answer": "Cherry Blossom"},
    {"question": "Who wrote 'The Catcher in the Rye'?", "answer": "J.D. Salinger"},
    {"question": "What is the capital of Russia?", "answer": "Moscow"},
    {"question": "Who wrote 'Frankenstein'?", "answer": "Mary Shelley"},
    {"question": "What is the national flower of Italy?", "answer": "Rose"},
    {"question": "Who wrote 'Crime and Punishment'?", "answer": "Fyodor Dostoevsky"},
    {"question": "What is the capital of Finland?", "answer": "Helsinki"},
    {"question": "Who wrote 'Jane Eyre'?", "answer": "Charlotte Bronte"},
    {"question": "What is the national flower of Germany?", "answer": "Cornflower"},
    {"question": "Who wrote 'Dracula'?", "answer": "Bram Stoker"},
    {"question": "What is the capital of China?", "answer": "Beijing"},
    {"question": "Who wrote 'The Odyssey'?", "answer": "Homer"},
    {"question": "What is the national flower of Spain?", "answer": "Red Carnation"},
    {"question": "Who wrote 'The Metamorphosis'?", "answer": "Franz Kafka"},
    {"question": "What is the capital of Ireland?", "answer": "Dublin"},
    {"question": "Who wrote 'The Canterbury Tales'?", "answer": "Geoffrey Chaucer"},
    {"question": "What is the national flower of France?", "answer": "Lily"},
    {"question": "Who wrote 'The Aeneid'?", "answer": "Virgil"},
    {"question": "What is the capital of Greece?", "answer": "Athens"},
    {"question": "Who wrote 'The Brothers Karamazov'?", "answer": "Fyodor Dostoevsky"},
    {"question": "What is the national flower of Russia?", "answer": "Sunflower"},
    {"question": "Who wrote 'The Great Gatsby'?", "answer": "F. Scott Fitzgerald"},
    {"question": "What is the capital of Peru?", "answer": "Lima"},
    {"question": "Who wrote 'Les Misérables'?", "answer": "Victor Hugo"},
    {"question": "What is the national flower of the United Kingdom?", "answer": "Rose"},
    {"question": "Who wrote 'War and Peace'?", "answer": "Leo Tolstoy"},
    {"question": "What is the capital of Argentina?", "answer": "Buenos Aires"},
    {"question": "Who wrote 'The Sound and the Fury'?", "answer": "William Faulkner"},
    {"question": "What is the national flower of Canada?", "answer": "Maple Leaf"},
]

random.shuffle(test_questions)
split_index = int(0.8 * len(test_questions))
train_data = test_questions[:split_index]
test_data = test_questions[split_index:]

# Simple Answer Verification
def is_correct(user_answer, correct_answer):
    return user_answer.strip().lower() == correct_answer.strip().lower()


# Question Answering System
def ask_question(question_data, use_advanced=False):
    question = question_data["question"]
    correct_answer = question_data["answer"]
    
    user_answer = input(f"Question: {question}\nYour answer: ")
    
    if is_correct:
        correct = is_correct(user_answer, correct_answer)
    else:
        correct = is_correct(user_answer, correct_answer)
        

    
    if correct:
        print("Correct!")
    else:
        print(f"Incorrect! The correct answer is: {correct_answer}")

# Example interaction
num_questions = int(input("How many questions would you like to answer? ")) 
for question_data in test_data[:num_questions]:  # Ask the first 5 questions from the test set
    ask_question(question_data, use_advanced=False)  # Set use_advanced=True to use the advanced verification
